#!/usr/bin/env bash

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/AHUAgent \
    -i platform.ahu4 \
    --config config/config/largeoffice/AHU4.config\
    --tag ahu \
    --start \
    --force
