#!/usr/bin/env bash

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/AHUAgent \
    -i platform.ahu2 \
    --config config/config/largeoffice/AHU2.config \
    --tag ahu \
    --start \
    --force
