#!/usr/bin/env bash

# Build a temp file string for use with the configuration

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavm1 \
     --config  config/config/largeoffice/Perimeter_mid_ZN_1_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/VAVAgent/ \
    -i platform.vavm2 \
    --config config/config/largeoffice/Perimeter_mid_ZN_2_CLGSETP.config \
    --tag vav \
    --start \
    --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavm3 \
     --config config/config/largeoffice/Perimeter_mid_ZN_3_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavm4 \
     --config config/config/largeoffice/Perimeter_mid_ZN_4_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavm5 \
     --config config/config/largeoffice/Core_mid_CLGSETP.config \
     --tag vav \
     --start \
     --force
