#!/usr/bin/env bash

# Build a temp file string for use with the configuration

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavt1 \
     --config  config/config/largeoffice/Perimeter_top_ZN_1_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/VAVAgent/ \
    -i platform.vavt2 \
    --config config/config/largeoffice/Perimeter_top_ZN_2_CLGSETP.config \
    --tag vav \
    --start \
    --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavt3 \
     --config config/config/largeoffice/Perimeter_top_ZN_3_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavt4 \
     --config config/config/largeoffice/Perimeter_top_ZN_4_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavt5 \
     --config config/config/largeoffice/Core_top_CLGSETP.config \
     --tag vav \
     --start \
     --force
