#!/usr/bin/env bash

# Build a temp file string for use with the configuration

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavb1 \
     --config  config/config/largeoffice/Perimeter_bot_ZN_1_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/VAVAgent/ \
    -i platform.vavb2 \
    --config config/config/largeoffice/Perimeter_bot_ZN_2_CLGSETP.config \
    --tag vav \
    --start \
    --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavb3 \
     --config config/config/largeoffice/Perimeter_bot_ZN_3_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavb4 \
     --config config/config/largeoffice/Perimeter_bot_ZN_4_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vavb5 \
     --config config/config/largeoffice/Core_bottom_CLGSETP.config \
     --tag vav \
     --start \
     --force
