#!/usr/bin/env bash

# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s transactivecontrol/ILCAgent/ \
    -i b1.ilc \
    --tag ilc \
    --config config/config/largeoffice/ilc/lo_ilc.config \
    --start \
    --force


