# Default arguments
# Can be changed by providing --build-arg IMAGE_TAG=bionic when building the image
ARG IMAGE_USER=amd64
ARG IMAGE_REPO=ubuntu
ARG IMAGE_TAG=focal

FROM ${IMAGE_USER}/${IMAGE_REPO}:${IMAGE_TAG} as volttron_base

SHELL [ "bash", "-c" ]

ENV OS_TYPE=${IMAGE_USER}
ENV DIST=${IMAGE_REPO}
ENV VOLTTRON_GIT_BRANCH=rabbitmq-volttron
ENV VOLTTRON_USER_HOME=/home/volttron
ENV VOLTTRON_HOME=${VOLTTRON_USER_HOME}/.volttron
ENV CODE_ROOT=/code
ENV VOLTTRON_ROOT=${CODE_ROOT}/volttron
ENV VOLTTRON_USER=volttron
ENV USER_PIP_BIN=${VOLTTRON_USER_HOME}/.local/bin
ENV RMQ_ROOT=${VOLTTRON_USER_HOME}/rabbitmq_server
ENV RMQ_HOME=${RMQ_ROOT}/rabbitmq_server-3.7.7

# --no-install-recommends \
USER root
RUN set -eux; apt-get update; apt-get install -y --no-install-recommends \
    procps \
    gosu \
    vim \
    tree \
    build-essential \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    openssl \
    libssl-dev \
    libevent-dev \
    git \
    gnupg \
    dirmngr \
    apt-transport-https \
    wget \
    curl \
    ca-certificates \
    libffi-dev

RUN id -u $VOLTTRON_USER &>/dev/null || adduser --disabled-password --gecos "" $VOLTTRON_USER

RUN mkdir -p /code && chown $VOLTTRON_USER.$VOLTTRON_USER /code
RUN echo "export PATH=/home/volttron/.local/bin:$PATH" > /home/volttron/.bashrc

############################################
# ENDING volttron_base image
############################################

FROM volttron_base AS volttron_core

RUN ln -s /usr/bin/pip3 /usr/bin/pip

USER $VOLTTRON_USER
# Assumes that volttron submodule has been installed via 'git submodule update --init --recursive'
# ownership must be hard coded becaue dockerfile doesn't recognize env commands for COPY

COPY --chown=volttron:volttron volttron /code/volttron
WORKDIR /code/volttron
# Installs the required dependencies under the 'install_requires' in the requirements.py under volttron
RUN pip3 install -e . --user
RUN echo "package installed at `date`"

USER root
RUN mkdir /startup $VOLTTRON_HOME && \
    chown $VOLTTRON_USER.$VOLTTRON_USER $VOLTTRON_HOME
COPY ./core/entrypoint.sh /startup/entrypoint.sh
COPY ./core/bootstart.sh /startup/bootstart.sh
COPY ./core/setup-platform.py /startup/setup-platform.py
COPY ./core/slogger.py /startup/slogger.py
COPY ./core/slogger.py /startup/slogger.py
RUN chmod +x /startup/*

############################################
# RABBITMQ SPECIFIC INSTALLATION
# Uncomment if RMQ is needed
############################################
#USER root
#RUN ./scripts/rabbit_dependencies.sh $OS_TYPE $DIST
#RUN python3 -m pip install gevent-pika
#
#USER $VOLTTRON_USER
#RUN mkdir $RMQ_ROOT
#RUN set -eux \
#    && wget -P $VOLTTRON_USER_HOME https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.7/rabbitmq-server-generic-unix-3.7.7.tar.xz \
#    && tar -xf $VOLTTRON_USER_HOME/rabbitmq-server-generic-unix-3.7.7.tar.xz --directory $RMQ_ROOT \
#    && $RMQ_HOME/sbin/rabbitmq-plugins enable rabbitmq_management rabbitmq_federation rabbitmq_federation_management rabbitmq_shovel rabbitmq_shovel_management rabbitmq_auth_mechanism_ssl rabbitmq_trust_store
############################################


############################################
# ENDING volttron_core image
############################################
FROM volttron_core AS volttron_tcc
ARG BUILDINGS

USER $VOLTTRON_USER

COPY --chown=volttron:volttron volttron-GS/base_market_agent /code/volttron/volttron/platform/agent/base_market_agent
COPY --chown=volttron:volttron volttron-GS/pnnl /code/volttron/volttron/pnnl

COPY --chown=volttron:volttron volttron-GS/TNSAgent /code/volttron/volttron/TNS_city_Agent
COPY --chown=volttron:volttron source/citysetup.py /code/volttron/volttron/TNS_city_Agent/setup.py

COPY --chown=volttron:volttron volttron-GS/TNSAgent /code/volttron/volttron/TNS_campus_Agent
COPY --chown=volttron:volttron source/campussetup.py /code/volttron/volttron/TNS_campus_Agent/setup.py

COPY --chown=volttron:volttron volttron-GS/TNSAgent /code/volttron/volttron/TNS_building_Agent
COPY --chown=volttron:volttron source/buildingsetup.py /code/volttron/volttron/TNS_building_Agent/setup.py

COPY --chown=volttron:volttron source/eplus /code/volttron/volttron/eplus

########################################

########################################
# The following lines should be run from any Dockerfile that
# is inheriting from this one as this will make the volttron
# run in the proper location.
#
# The user must be root at this point to allow gosu to work
########################################
USER root
WORKDIR ${VOLTTRON_USER_HOME}
ENTRYPOINT ["/startup/entrypoint.sh"]
CMD ["/startup/bootstart.sh"]