#!/usr/bin/env bash

python scripts/install-agent.py \
    -i platform.historian \
    -s services/core/SQLHistorian \
    -c config/config/brsw/ilc/config.sqlite \
    --tag sqlite-db \
    --start \
    --force

