#!/usr/bin/env bash
#!/usr/bin/env bash

export CONFIG=$(mktemp /tmp/abc-script.XXXXXX)

cat > $CONFIG <<EOL
{
    "agentid": "sqlhistorian-sqlite",
    "identity": "platform.historian",
    "connection": {
        "type": "sqlite",
        "params": {
            "database": "~/volttron/log/smalloffice_tns.sqlite"
        }
    },
    "capture_device_data": true,
    "capture_analysis_data": false,
    "capture_log_data": false,
    "capture_record_data": false,
    "custom_topics": {
        "other_topic": ["tnc"]
    }
}
EOL

python scripts/install-agent.py \
    -i platform.historian \
    -s services/core/SQLHistorian \
    -c $CONFIG \
    --tag sqlite-db \
    --start \
    --force
rm $CONFIG