#!/bin/bash
. env/bin/activate
pip install pandas sympy transitions
volttron -vv -l /home/volttron/volttron/log/tns.log > /dev/null 2>&1&
sleep 5
. upgrade-scripts/campus_city/upgrade-sqlite-historian
. upgrade-scripts/campus_city/upgrade-lo-forwarder
. upgrade-scripts/campus_city/upgrade-b1-forwarder
. upgrade-scripts/campus_city/upgrade-so-forwarder
. upgrade-scripts/campus_city/upgrade-brsw-forwarder
. upgrade-scripts/campus_city/upgrade-tns-campus
. upgrade-scripts/upgrade_listener
while : ;do
    [[ -f "/home/volttron/volttron/log/tns.log" ]] && grep -q "devices/PNNL/BUILDING1/AHU2/all" "/home/volttron/volttron/log/tns.log" && echo "FOUND" && break
    sleep 5
done
. upgrade-scripts/campus_city/upgrade-tns-city
. upgrade-scripts/upgrade_listener

while : ;do
    [[ -f "/home/volttron/volttron/log/tns.log"  ]] && grep -q "'TimeStamp': '2017-08-31 59:59:00Z', 'min_compatible_version': '3.0', 'max_compatible_version': '', 'X-Forwarded': True, 'X-Forwarded-From': 'simulation_b1'" "/home/volttron/volttron/log/tns.log" && echo "Completed" && break
    sleep 5
done