#!/bin/bash

. env/bin/activate
pip install decorators
pip install pandas sympy transitions


volttron -vv -l /home/volttron/volttron/log/lo.log > /dev/null 2>&1&
sleep 10

. upgrade-scripts/largeoffice/upgrade-sqlite-historian
. upgrade-scripts/largeoffice/upgrade-ahu1-vav
. upgrade-scripts/largeoffice/upgrade-ahu2-vav
. upgrade-scripts/largeoffice/upgrade-ahu3-vav
. upgrade-scripts/largeoffice/upgrade-ahu4-vav
. upgrade-scripts/largeoffice/upgrade-ahu1
. upgrade-scripts/largeoffice/upgrade-ahu2
. upgrade-scripts/largeoffice/upgrade-ahu3
. upgrade-scripts/largeoffice/upgrade-ahu4
. upgrade-scripts/largeoffice/upgrade-light
. upgrade-scripts/largeoffice/upgrade-uncontrol-agent
. upgrade-scripts/largeoffice/upgrade-market-service
. upgrade-scripts/largeoffice/upgrade-building-agent
. upgrade-scripts/largeoffice/upgrade-energyplus
. upgrade-scripts/largeoffice/upgrade-pnnl-forwarder
. upgrade-scripts/upgrade_listener

while : ;do
    [[ -f "/home/volttron/volttron/log/lo.log" ]] && grep -q "Simulation reached end" "/home/volttron/volttron/log/lo.log" && echo "Done" && break
    sleep 5
done