#!/usr/bin/env bash

# Build a temp file string for use with the configuration

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light1 \
     --config config/config/smalloffice/lighting1.config \
     --tag light \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light2 \
     --config config/config/smalloffice/lighting2.config \
     --tag light \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light3 \
     --config config/config/smalloffice/lighting3.config \
     --tag light \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light4 \
     --config config/config/smalloffice/lighting4.config \
     --tag light \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light5 \
     --config config/config/smalloffice/lighting5.config \
     --tag light \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light6 \
     --config config/config/smalloffice/lighting6.config \
     --tag light \
     --start \
     --force
     
python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light7 \
     --config config/config/smalloffice/lighting7.config \
     --tag light \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light8 \
     --config config/config/smalloffice/lighting8.config \
     --tag light \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light9 \
     --config config/config/smalloffice/lighting9.config \
     --tag light \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/LightingAgent \
     -i platform.light10 \
     --config config/config/smalloffice/lighting10.config \
     --tag light \
     --start \
     --force