#!/bin/bash
. env/bin/activate
pip install pandas transitions sympy

volttron -vv -l /home/volttron/volttron/log/brsw.log > /dev/null 2>&1&
sleep 10
. upgrade-scripts/brsw/upgrade-sqlite-historian
. upgrade-scripts/brsw/upgrade-rtu
. upgrade-scripts/brsw/upgrade-uncontrol-agent
. upgrade-scripts/brsw/upgrade-market-service
. upgrade-scripts/brsw/upgrade-building-agent
. upgrade-scripts/brsw/upgrade-energyplus
. upgrade-scripts/brsw/upgrade-pnnl-forwarder
. upgrade-scripts/upgrade_listener

while : ;do
    [[ -f "/home/volttron/volttron/log/brsw.log" ]] && grep -q "Simulation reached end" "/home/volttron/volttron/log/brsw.log" && echo "Done" && break
    sleep 5
done