#!/bin/bash
. env/bin/activate
pip install pandas sympy transitions

volttron -vv -l volttron.log > /dev/null 2>&1&
sleep 5
. upgrade-scripts/smalloffice/upgrade-sqlite-historian
. upgrade-scripts/smalloffice/upgrade-rtu
. upgrade-scripts/smalloffice/upgrade-light
. upgrade-scripts/smalloffice/upgrade-uncontrol
. upgrade-scripts/smalloffice/upgrade-market-service
. upgrade-scripts/smalloffice/upgrade-building-agent
. upgrade-scripts/smalloffice/upgrade-energyplus
. upgrade-scripts/smalloffice/upgrade-pnnl-forwarder
. upgrade-scripts/upgrade_listener