#!/bin/bash

. env/bin/activate
pip install decorators
pip install pandas
pip install scipy patsy transitions sympy

volttron -vv -l volttron.log > /dev/null 2>&1&
sleep 15
. upgrade-scripts/largeoffice/ilc/upgrade-sqlite-historian
sleep 2
. upgrade-scripts/largeoffice/ilc/upgrade-ilc
. upgrade-scripts/largeoffice/ilc/upgrade-energyplus
. upgrade-scripts/upgrade_listener