#!/usr/bin/env bash

# Build a temp file string for use with the configuration

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/RTUAgent \
     -i platform.rtu1 \
     --config config/config/brsw/CSP1.config \
     --tag rtu \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/RTUAgent \
     -i platform.rtu2 \
     --config config/config/brsw/CSP2.config \
     --tag rtu \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/RTUAgent \
     -i platform.rtu3 \
     --config config/config/brsw/CSP3.config \
     --tag rtu \
     --start \
     --force
     
python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/RTUAgent \
     -i platform.rtu4 \
     --config config/config/brsw/CSP4.config \
     --tag rtu \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/RTUAgent \
     -i platform.rtu5 \
     --config config/config/brsw/CSP5.config \
     --tag rtu \
     --start \
     --force

