#!/usr/bin/env bash

# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s transactivecontrol/ILCAgent/ \
    -i brws.ilc \
    --tag ilc \
    --config config/config/building1/ilc/b1_ilc.config \
    --start \
    --force


