#!/usr/bin/env bash

# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s transactivecontrol/ILCAgent/ \
    -i so.ilc \
    --tag ilc \
    --config config/config/smalloffice/ilc/so_ilc.config \
    --start \
    --force


