#!/usr/bin/env bash

# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s transactivecontrol/pnnl/energyplusagent \
    -i platform.actuator \
    --tag eplus \
    --config config/config/largeoffice/ep_LargeOffice.config \
    --start \
    --force


