#!/usr/bin/env bash

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightb1 \
    --config config/config/largeoffice/Perimeter_bot_ZN_1_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightb2 \
    --config config/config/largeoffice/Perimeter_bot_ZN_2_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightb3 \
    --config config/config/largeoffice/Perimeter_bot_ZN_3_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightb4 \
    --config config/config/largeoffice/Perimeter_bot_ZN_4_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightm1 \
    --config config/config/largeoffice/Perimeter_mid_ZN_1_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightm2 \
    --config config/config/largeoffice/Perimeter_mid_ZN_2_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightm3 \
    --config config/config/largeoffice/Perimeter_mid_ZN_3_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightm4 \
    --config config/config/largeoffice/Perimeter_mid_ZN_4_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightt1 \
    --config config/config/largeoffice/Perimeter_top_ZN_1_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightt2 \
    --config config/config/largeoffice/Perimeter_top_ZN_2_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightt3 \
    --config config/config/largeoffice/Perimeter_top_ZN_3_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightt4 \
    --config config/config/largeoffice/Perimeter_top_ZN_4_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightb5 \
    --config config/config/largeoffice/Core_bottom_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightm5 \
    --config config/config/largeoffice/Core_mid_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightt5 \
    --config config/config/largeoffice/Core_top_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/LightingAgent \
    -i platform.lightb \
    --config config/config/largeoffice/Basement_BLDG_LIGHT.config \
    --tag light \
    --start \
    --force