#!/usr/bin/env bash

python ./scripts/install-agent.py \
    -s transactivecontrol/ModelRegressionAgent/ \
    -i platform.regression_ahu1 \
    --config config/config/building1/regression_ahu1.config \
    --tag regression \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/ModelRegressionAgent/ \
    -i platform.regression_ahu2 \
    --config config/config/building1/regression_ahu2.config \
    --tag regression \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/ModelRegressionAgent/ \
    -i platform.regression_ahu3 \
    --config config/config/building1/regression_ahu3.config \
    --tag regression \
    --start \
    --force

python ./scripts/install-agent.py \
    -s transactivecontrol/ModelRegressionAgent/ \
    -i platform.regression_ahu4 \
    --config config/config/building1/regression_ahu4.config \
    --tag regression \
    --start \
    --force
