#!/usr/bin/env bash

# Build a temp file string for use with the configuration

 python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav104 \
     --config config/config/building1/104_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/VAVAgent/ \
    -i platform.vav105\
    --config config/config/building1/105_CLGSETP.config \
    --tag vav \
    --start \
    --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav107 \
     --config config/config/building1/107_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav108\
     --config config/config/building1/108_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav112\
     --config config/config/building1/112_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav116\
     --config config/config/building1/116_CLGSETP.config \
     --tag vav \
     --start \
     --force
