#!/usr/bin/env bash

# Build a temp file string for use with the configuration

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav100 \
     --config  config/config/building1/100_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/VAVAgent/ \
    -i platform.vav102 \
    --config config/config/building1/102_CLGSETP.config \
    --tag vav \
    --start \
    --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav118 \
     --config config/config/building1/118_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav119 \
     --config config/config/building1/119_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav120 \
     --config config/config/building1/120_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav121 \
     --config config/config/building1/121_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent/ \
     -i platform.vav123a \
     --config config/config/building1/123A_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/VAVAgent/ \
    -i platform.vav123b \
    --config config/config/building1/123B_CLGSETP.config \
    --tag vav \
    --start \
    --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent \
     -i platform.vav127a \
     --config config/config/building1/127A_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent \
     -i platform.vav127b \
     --config config/config/building1/127B_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent \
     -i platform.vav129 \
     --config config/config/building1/129_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent \
     -i platform.vav131 \
     --config config/config/building1/131_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent \
     -i platform.vav133 \
     --config config/config/building1/133_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/VAVAgent \
    -i platform.vav136 \
    --config config/config/building1/136_CLGSETP.config \
    --tag vav \
    --start \
    --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent \
     -i platform.vav142 \
     --config config/config/building1/142_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent \
     -i platform.vav143 \
     --config config/config/building1/143_CLGSETP.config \
     --tag vav \
     --start \
     --force

python ./scripts/install-agent.py \
     -s transactivecontrol/MarketAgents/VAVAgent \
     -i platform.vav150 \
     --config config/config/building1/150_CLGSETP.config \
     --tag vav \
     --start \
     --force
