#!/usr/bin/env bash

# Build a temp file string for use with the configuration

python ./scripts/install-agent.py \
    -s transactivecontrol/MarketAgents/VAVAgent/ \
    -i platform.vav2 \
    --config config/config/building1/002_CLGSETP.config \
    --tag vav \
    --start \
    --force
